minesweeper/config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :boards, only: %i[index show create]
  root "pages#home"
end

minesweeper/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

minesweeper/app/models/board.rb
class Board < ApplicationRecord
  validates :name, :email, :height, :width, :mines_number, presence: true
  validates :name, uniqueness: true
  validates :name, length: { maximum: 30 }
  validates :email, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
  validates :height, :width, numericality: { greater_than_or_equal_to: 2 }
  validates :mines_number, numericality: { greater_than_or_equal_to: 0 }
  validate :less_mines_than_board_area?

  after_validation :set_slug, only: [:create]

  scope :recently_created, -> { order(created_at: :desc).limit(10) }
  scope :order_by_name, -> { order(name: :asc) }
  scope :order_by_size, -> { order(Arel.sql('height * width DESC')) }
  scope :order_by_difficulty, -> { order(Arel.sql('height * width / mines_number DESC')) }


  def self.search(search_param)
    return Board.all unless search_param.present?

    Board.where('name ~* :search_param OR email ~* :search_param', search_param: search_param)
  end

  def to_param
    "#{id}-#{slug}"
  end

  private

  def less_mines_than_board_area?
    return unless [height, width, mines_number].all?(&:present?)

    return if mines_number <= height * width

    errors.add(:mines_number, 'must be less than the area of the board')
  end

  def set_slug
    return unless name.present?

    self.slug = name.parameterize
  end
end

minesweeper/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

minesweeper/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[show]

  def index
    @boards = Board.search(params[:query])
    @boards = sort_boards(@boards)

    @boards = @boards.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)

    if @board.save
      # BoardMailer.board_generated_email(@board).deliver_now
      redirect_to board_url @board, notice: 'Successfully created.'
    else
      flash[:alert] = 'Invalid data'
    end
  end

  private

  def sort_boards(boards)
    case params[:sort]
    when "by_size"
      boards.order_by_size
    when "by_name"
      boards.order_by_name
    when "by_difficulty"
      boards.order_by_difficulty
    else
      boards
    end
  end

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(
      :name,
      :email,
      :height,
      :width,
      :mines_number,
      :query
    )
  end
end

minesweeper/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @board = Board.new
    @boards = Board.recently_created
  end
end

minesweeper/app/helpers/application_helper.rb
module ApplicationHelper
end

minesweeper/app/helpers/boards_helper.rb
module BoardsHelper

  def get_board_technical_representation(board)
    BoardGeneratorService.new(board).call
  end

  def get_cell_value(value)
    value.nil? ? ' ' : 'X'
  end
end

minesweeper/app/helpers/pages_helper.rb
module PagesHelper
end

minesweeper/app/views/boards/_board.html.erb
<% if @board %>
  <% representation = get_board_technical_representation(@board) %>
  <div class="d-flex">
    <div class="d-flex flex-column gap-3 limited-width">
      <p>Name: <%= @board.name %></p>
      <p>Email: <%= @board.email %></p>
      <p>Height: <%= @board.height %></p>
      <p>Width: <%= @board.width %></p>
      <p>No. of mines: <%= @board.mines_number %></p>
      <p>Representation: <%= representation %></p>
    </div>

    <div class="minefield-container">
      <table style="border: 1px solid black;">
        <% representation.each do |row| %>
          <tr>
            <% row.each do |cell| %>
              <td style="border: 1px solid black; padding: 10px;">
                <%= get_cell_value(cell) %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

minesweeper/app/views/boards/_boards.html.erb
<table class="table m-5">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Author email</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    <% if @boards.present? %>
      <% @boards.each do |board| %>
        <tr>
          <td><%= link_to board.name, board_path(board) %></td>
          <td><%= board.email %></td>
          <td><%= l(board.created_at, format: :short) %></td>
        </tr>
      <% end %>
    <% else %>
      <p class="m-3">No boards to show</p>
    <% end %>
  </tbody>
</table>

minesweeper/app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
	<div class="form-group w-75">
		<%= f.label :email, "Email" %>
		<%= f.email_field :email, class: 'form-control' %>
	</div>

	<div class="form-group w-75">
		<%= f.label :name, "Name" %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<div class="form-group mt-3 w-75 h-25 d-flex gap-3">
    <div class="d-flex flex-column">
      <%= f.label :height, "Height" %>
      <%= f.number_field :height, value: 2, class: 'form-control', min: 2 %>
    </div>

    <div>
      <%= f.label :width, "Width" %>
      <%= f.number_field :width, value: 2, class: 'form-control', min: 2 %>
    </div>

    <div>
      <%= f.label :mines_number, "No. of mines" %>
      <%= f.number_field :mines_number, value: 0, class: 'form-control', min: 0 %>
    </div>

    <div class="mt-4">
      <%= f.submit "Generate board", class: 'btn btn-success' %>
    </div>
	</div>
<% end %>

minesweeper/app/views/boards/index.html.erb
<div class="boards-container d-flex flex-column align-items-center" style="margin-left: 600px">
  <h1 class="m-5">
    <%= link_to 'All boards', boards_path, class: 'm-5' %>
  </h1>
  <%= render 'layouts/partials/sorting-component' %>
  <%= render 'layouts/partials/search-bar' %>
  <%= render 'boards' %>
  <div class="m-5 mt-0"><%= paginate @boards %></div>
</div>

minesweeper/app/views/boards/show.html.erb
<div class="d-flex flex-column">
  <header class="d-flex">
    <h3 class="w-100 text-center">
      Board
    </h3>
  </header>

  <div class="d-flex flex-column align-items-center m-5">
  <%= render @board %>
  </div>
</div>

minesweeper/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/partials/navbar' %>
    <div class="page-container d-flex">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/partials/footer' %>
  </body>
</html>

minesweeper/app/views/layouts/partials/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    made by Bruno
  </div>
</div>

minesweeper/app/views/layouts/partials/_navbar.html.erb
<nav class="navbar w-100 navbar-expand-lg navbar-dark fixed-top bg-dark">
  <div class="logo text-center text-white">
    <%= link_to 'One step minesweeper', root_path, style: 'text-decoration: none; color: white;' %>
  </div>
  <div class="nav-links">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "home-link" %>
      </li>
    </ul>
  </div>
</nav>
<div class="card-category"></div>

minesweeper/app/views/layouts/partials/_search-bar.html.erb
<div class="search-box-container">
  <%= form_with(url: boards_path, method: "get") do |form| %>
    <%= form.text_field :query %>
    <%= form.submit "Search" %>
  <% end %>
</div>

minesweeper/app/views/layouts/partials/_sorting-component.html.erb
<div class="dropdown">
  <button class="dropbtn">Sort by</button>
  <div class="dropdown-content">
    <%= link_to "biggest to smallest", boards_path(sort: "by_size") %>
    <%= link_to "hardest to easiest", boards_path(sort: "by_difficulty") %>
    <%= link_to "Alphabetically", boards_path(sort: "by_name") %>
  </div>
</div>

minesweeper/app/views/pages/home.html.erb
<div class="container d-flex align-items-center justify-content-center vh-100">
  <div class="d-flex flex-column justify-content-start">
    <div class="m-5">
      <h4>Create your minefield</h4>
      <%= render 'boards/form' %>
    </div>

    <div class="home-table d-flex flex-column">
      <div class="d-flex justify-content-between">
        <h4>10 most recent boards</h4>
        <h6><%= link_to 'View all generated boards', boards_path %></h6>
      </div>
      <%= render 'boards/boards' %>
    </div>
  </div>
</div>